server:
  port: 8978

# File system access (same mapping as Sonarr, Radarr and Jellyfin) is required to delete seasons by season and create "Leaving Soon" collections in Jellyfin
# Currently, Jellyfin does not support an easy way to add only a few seasons or movies to a collection, we need access to temporary hardlinks
# Additionally, checks to prevent deletion on currently still seeding media currently require file system access as well
file-system:
  access: true

application:
  dry-run: true
  movie-expiration: 90d # 3 months - if a movie's files on your system are older than this, they will be deleted
  season-expiration: 60d # 2 months - if a season's files on your system are older than this, they will be deleted

clients:
  sonarr:
    url: "http://localhost:8989"
    api-key: "4ed7f4d0e8584d65aa2d47d944077ff6"
  radarr:
    url: "http://localhost:7878"
    api-key: "cd0912f129d348c9b69bb20d49fcbe44"
  jellyfin:
    url: "http://localhost:8096"
    api-key: "4da8d93992804489ba2d1f0e31b8316c"
  jellyseerr:
    url: "http://localhost:5055"
    api-key: "MTY3NzU3NzI0NzgzOWFhNWYxMGE4LWNlMWYtNDc1ZS04ODYzLThkMjQyMTQ4M2NiZCe="

# Currently not in use - intended to check seeding status and not delete currently seeding media
  torrent:
    type: QBITTORRENT
    name: qBittorrent
    auto-resume: true
    url: "locahost:8080"
    username: admin
    password: adminadmin
